//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWLNBazarHub.EnlaceDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBazar2Entities1 : DbContext
    {
        public DBBazar2Entities1()
            : base("name=DBBazar2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarritoCompras> CarritoCompras { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<ComentariosValoraciones> ComentariosValoraciones { get; set; }
        public virtual DbSet<DetallesFactura> DetallesFactura { get; set; }
        public virtual DbSet<DetallesPedido> DetallesPedido { get; set; }
        public virtual DbSet<Devoluciones> Devoluciones { get; set; }
        public virtual DbSet<DireccionesEnvio> DireccionesEnvio { get; set; }
        public virtual DbSet<EnviosSeguimiento> EnviosSeguimiento { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<HistorialTransacciones> HistorialTransacciones { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<MetodosPago> MetodosPago { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<PromocionesDescuentos> PromocionesDescuentos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<ReportesAnalisis> ReportesAnalisis { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
