//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWLNBazarHub.EnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosValoraciones
    {
        public int ComentarioID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Valoracion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
