//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWLNBazarHub.EnlaceDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialTransacciones
    {
        public int TransaccionID { get; set; }
        public string TipoTransaccion { get; set; }
        public Nullable<int> IDTransaccion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
